# Generated by Django 6.0.4 on 2026-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
